version: "3"

services:
  metabase:
    restart: "always"
    image: "metabase/metabase"
    volumes:
      - ./data/metabase:/metabase-data
    env_file:
      - ./config/metabase.env
    ports:
      - '3000:3000'
    network_mode: "host"
