version: "3"

services:
  metabase:
    container_name: "metabase"
    restart: "always"
    image: "metabase/metabase"
    env_file:
      - ./config/metabase.env
    ports:
      - '3000:3000'
    network_mode: "host"
